version: "3"
services: 
  springboot-app:
    container_name: spring-app
    image: spring-app
    restart: always
    build: .
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    ports: 
     - 3345:3306  
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_ROOT_PASSWORD: root